title: godel.club
email: info@godel.club
description: >- # this means to ignore newlines until "baseurl:"
  foobarbaz
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll
permalink: /blog/:title.html

theme: null
paginate: 5
paginate_path: 'page/:num'
plugins:
  - jekyll-paginate
  - jekyll-feed

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
